<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SyntheticTH-b5e8c5a9-643a-461d-be38-28bd0e56bba9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alexinea.Extensions.Configuration.Toml" Version="7.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.toml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
